name: Trigger auto deployment for tailwind-traders-carts987654

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ mithun/lab3 ]
    paths:
    - '**'
    - '.github/workflows/tailwind-traders-carts987654-AutoDeployTrigger-09cdd845-6974-4df7-8516-5fff5cdf81a2.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: tailwindtradersacr987654.azurecr.io
          username: ${{ secrets.TAILWINDTRADERSCARTS987654_REGISTRY_USERNAME }}
          password: ${{ secrets.TAILWINDTRADERSCARTS987654_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: tailwindtradersacr987654.azurecr.io/tailwind-traders-carts987654:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.TAILWINDTRADERSCARTS987654_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n tailwind-traders-carts987654 -g tailwind-traders-rg --server tailwindtradersacr987654.azurecr.io --username  ${{ secrets.TAILWINDTRADERSCARTS987654_REGISTRY_USERNAME }} --password ${{ secrets.TAILWINDTRADERSCARTS987654_REGISTRY_PASSWORD }}
            az containerapp update -n tailwind-traders-carts987654 -g tailwind-traders-rg --image tailwindtradersacr987654.azurecr.io/tailwind-traders-carts987654:${{ github.sha }}
